### ISSUE TITLE
Ping integration issues

### ISSUE THREAD

**Issue by srisgajare** [DataDog/integrations-extras#1084]
I am unable to use the ping integration sucessfully to monitor my hosts
**Output of the [info page](https://docs.datadoghq.com/integrations/ping/)**

```text
ping (1.0.2)
    ------------
      Instance ID: ping:bf57e8d4f2230bb1 [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/ping.d/conf.yaml
      Total Runs: 2
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 2ms
      Last Execution Date : 2021-11-22 23:56:16 UTC (1637625376000)
      Last Successful Execution Date : Never
      Error: get_subprocess_output expected output but had none.
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 1006, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/ping/ping.py", line 65, in check
          lines = self._exec_ping(timeout, host)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/ping/ping.py", line 48, in _exec_ping
          lines, err, retcode = get_subprocess_output(
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/utils/subprocess_output.py", line 56, in get_subprocess_output
          out, err, returncode = subprocess_output(cmd_args, raise_on_empty_output, env=env)
      _util.SubprocessOutputEmptyError: get_subprocess_output expected output but had none.
      Instance ID: ping:ee3892c0589f055c [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/ping.d/conf.yaml
      Total Runs: 2
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 4ms
      Last Execution Date : 2021-11-22 23:56:09 UTC (1637625369000)
      Last Successful Execution Date : Never
      Error: get_subprocess_output expected output but had none.
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 1006, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/ping/ping.py", line 65, in check
          lines = self._exec_ping(timeout, host)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/ping/ping.py", line 48, in _exec_ping
          lines, err, retcode = get_subprocess_output(
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/utils/subprocess_output.py", line 56, in get_subprocess_output
          out, err, returncode = subprocess_output(cmd_args, raise_on_empty_output, env=env)
      _util.SubprocessOutputEmptyError: get_subprocess_output expected output but had none.
```

**Additional environment details (Operating System, Cloud provider, etc):**
I am running the agent on Ubuntu 18.04 VM

**Steps to reproduce the issue:**
1. Built the integration for the docker container using the following steps in the [link](https://docs.datadoghq.com/agent/guide/use-community-integrations/?tab=docker)
2. Used the same [sample file](https://github.com/DataDog/integrations-extras/blob/master/ping/datadog_checks/ping/data/conf.yaml.example) I just replaced the host_name with the IPs of the host I want to monitor
3. I am able to ping the hosts from the docker hosts

**Comment by srisgajare** [comment]
Can I get any update on this issue?

**Comment by tuan-nguyen-ts** [comment]
@jstanton617 I'm having this issue, too.

**Comment by yzhan289** [comment]
@tuan-nguyen-ts @srisgajare Can you try installing the `ping` binary on the host? I was able to replicate this issue on a Ubuntu test container, and running `apt-get install iputils-ping` resolved my issue. The ping integration basically just tries to run the `ping` command, although the ping binary is not included by default. I've made a [PR updating the README](https://github.com/DataDog/integrations-extras/pull/1557) for this contributor integration to make it clear. Let me know if this fixes the issue!

**Comment by tuan-nguyen-ts** [comment]
Thank you @yzhan289 , installing ping binary fixed the issue. Now it's working as expected.

**Comment by yzhan289** [comment]
@tuan-nguyen-ts Glad to hear! I'll close this ticket for now, but if @srisgajare your issue is not solved by installing the `ping` binary, please feel free to reopen the issue.
