### ISSUE TITLE
Install error of redis-sentinel

### ISSUE THREAD

**Issue by andrescolodrero** [DataDog/integrations-extras#1098]
Hi,
m having an error during install.. not sure if due to proxy problems

datadog-agent integration install -t datadog-redis_sentinel==1.1.0 --allow-root 

is there a way to add proxy settings or manual install?

Traceback (most recent call last):
  File "/opt/datadog-agent/embedded/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/datadog-agent/embedded/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/downloader/__main__.py", line 9, in <module>
    sys.exit(download())
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/downloader/cli.py", line 115, in download
    tuf_downloader = TUFDownloader(
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/downloader/download.py", line 106, in __init__
    self.__updater.refresh()
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/tuf/client/updater.py", line 1080, in refresh
    self._update_root_metadata(root_metadata)
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/tuf/client/updater.py", line 1147, in _update_root_metadata
    self._update_metadata('root', DEFAULT_ROOT_UPPERLENGTH,
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/tuf/client/updater.py", line 1696, in _update_metadata
    self._get_metadata_file(metadata_role, remote_filename,
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/tuf/client/updater.py", line 1621, in _get_metadata_file
    raise exceptions.NoWorkingMirrorError(file_mirror_errors)
tuf.exceptions.NoWorkingMirrorError: No working mirror was found:
  'dd-integrations-core-wheels-build-stable.datadoghq.com': ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='dd-integrations-core-wheels-build-stable.datadoghq.com', port=443): Read timed out. (read timeout=60)"))

**Comment by andrescolodrero** [comment]
Fixed by adding proxy settings to Datadog.yaml
