### ISSUE TITLE
[Filebeat] Error when parsing the registry file

### ISSUE THREAD

**Issue by martonsz** [DataDog/integrations-extras#150]
I get the following error when I try to use the [filebeat integration](https://github.com/DataDog/integrations-extras/tree/master/filebeat)

Error shown when running `agent status`

```
filebeat
    --------
      Total Runs: 2
      Metrics: 0, Total Metrics: 0
      Events: 0, Total Events: 0
      Service Checks: 0, Total Service Checks: 0
      Average Execution Time : 0ms
      Error: 'list' object has no attribute 'itervalues'
      Traceback (most recent call last):
        File "/opt/datadog-agent/bin/agent/dist/checks/__init__.py", line 332, in run
          self.check(copy.deepcopy(self.instances[0]))
        File "/etc/datadog-agent/checks.d/filebeat.py", line 30, in check
          for item in registry_contents.itervalues():
      AttributeError: 'list' object has no attribute 'itervalues'
```

# System

Google Kubernetes Engine - Kubernetes 1.10.2-gk.3
OS: Container-Optimized OS (Chrome OS)
Datadog agent: 6.2.1-jmx

# My registry file

The registry file that the filebeat integration tried to parse.

```json
[
  {
    "FileStateOS": {
      "device": 2049,
      "inode": 8062
    },
    "offset": 123177,
    "source": "/var/lib/docker/containers/3395bc9e8f76c040e2a7cb3d10ac00415084e62bad3ebd11bee8aaa6286e0612/3395bc9e8f76c040e2a7cb3d10ac00415084e62bad3ebd11bee8aaa6286e0612-json.log",
    "timestamp": "2018-06-07T12:48:41.184566453Z",
    "ttl": -1,
    "type": "docker"
  },
  {
    "FileStateOS": {
      "device": 2049,
      "inode": 415428
    },
    "offset": 869,
    "source": "/var/lib/docker/containers/df4b8d396dfad06a164e89dad7a1f8369201496518f8e8703cc11e05b30ab828/df4b8d396dfad06a164e89dad7a1f8369201496518f8e8703cc11e05b30ab828-json.log",
    "timestamp": "2018-06-07T09:58:43.408651902Z",
    "ttl": -2,
    "type": "docker"
  },
  {
    "FileStateOS": {
      "device": 2049,
      "inode": 8082
    },
    "offset": 0,
    "source": "/var/lib/docker/containers/7d07de469a0fbe34f43abce50c22537a1673207899e94875e4876eda8bb49504/7d07de469a0fbe34f43abce50c22537a1673207899e94875e4876eda8bb49504-json.log",
    "timestamp": "2018-06-07T12:46:32.196587691Z",
    "ttl": -1,
    "type": "docker"
  },
  {
    "FileStateOS": {
      "device": 2049,
      "inode": 8155
    },
    "offset": 0,
    "source": "/var/lib/docker/containers/ab9ccfe73d0c2779f8f7985d17551a083221157ed4e467707d4cd2d15612e128/ab9ccfe73d0c2779f8f7985d17551a083221157ed4e467707d4cd2d15612e128-json.log",
    "timestamp": "2018-06-07T09:39:56.976326151Z",
    "ttl": -2,
    "type": "docker"
  },
  {
    "FileStateOS": {
      "device": 2049,
      "inode": 410824
    },
    "offset": 376359,
    "source": "/var/lib/docker/containers/cd55e2c8163d620ba31d7c547c948075d7a71b7e3841576c02fa76b0a4034c17/cd55e2c8163d620ba31d7c547c948075d7a71b7e3841576c02fa76b0a4034c17-json.log",
    "timestamp": "2018-06-07T12:05:38.478044287Z",
    "ttl": -2,
    "type": "docker"
  },
  {
    "FileStateOS": {
      "device": 2049,
      "inode": 410890
    },
    "offset": 1581,
    "source": "/var/lib/docker/containers/fe61754255ee3d70587a24684405010365a55968a7fa5578e57bf6713b38772e/fe61754255ee3d70587a24684405010365a55968a7fa5578e57bf6713b38772e-json.log",
    "timestamp": "2018-06-07T12:46:33.193958253Z",
    "ttl": -1,
    "type": "docker"
  },
  {
    "FileStateOS": {
      "device": 2049,
      "inode": 411014
    },
    "offset": 1148421,
    "source": "/var/lib/docker/containers/42ec4df378748a7975399ab4eacebf1a10426e4bcbfc370781a77dc441c5d64d/42ec4df378748a7975399ab4eacebf1a10426e4bcbfc370781a77dc441c5d64d-json.log",
    "timestamp": "2018-06-07T12:50:50.193160614Z",
    "ttl": -1,
    "type": "docker"
  },
  {
    "FileStateOS": {
      "device": 2049,
      "inode": 411064
    },
    "offset": 1610,
    "source": "/var/lib/docker/containers/d97a48995bfc3324ec87bd8517bb624209eb1629a2d880730326aa7626154463/d97a48995bfc3324ec87bd8517bb624209eb1629a2d880730326aa7626154463-json.log",
    "timestamp": "2018-06-07T12:46:32.184737588Z",
    "ttl": -1,
    "type": "docker"
  },
  {
    "FileStateOS": {
      "device": 2049,
      "inode": 421663
    },
    "offset": 81940,
    "source": "/var/lib/docker/containers/84d7a8b98a0d99713a04e3f97bc7a914067166d78e8ace55da8bf05cf8ab0d58/84d7a8b98a0d99713a04e3f97bc7a914067166d78e8ace55da8bf05cf8ab0d58-json.log",
    "timestamp": "2018-06-07T12:50:55.72736397Z",
    "ttl": -1,
    "type": "docker"
  },
  {
    "FileStateOS": {
      "device": 2049,
      "inode": 673791
    },
    "offset": 149914,
    "source": "/var/lib/docker/containers/5517b5b6319e111f3d9feb7ccf5bbf08c645062dc345c62c9e765a6eadb3b75b/5517b5b6319e111f3d9feb7ccf5bbf08c645062dc345c62c9e765a6eadb3b75b-json.log",
    "timestamp": "2018-06-07T12:46:06.2639707Z",
    "ttl": -2,
    "type": "docker"
  }
]
```

**Comment by danielkasen** [comment]
This should be fixed with the newest version. Since it appears to drop the itervalues call.

**Comment by martonsz** [comment]
This is fixed in https://github.com/DataDog/integrations-extras/pull/189
