### ISSUE TITLE
problem with setup_env

### ISSUE THREAD

**Issue by technovangelist** [DataDog/integrations-extras#16]
here is what i see when running `rake setup_env`:

```
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-27.2.0.zip
Extracting in /var/folders/pk/q2qft9p95312_pm_q5z9_mk00000gn/T/tmptTZWQY
Traceback (most recent call last):
  File "/Users/mattw/Projects/DatadogRepos/integrations-extras-pagespeed/venv/ez_setup.py", line 426, in <module>
    sys.exit(main())
  File "/Users/mattw/Projects/DatadogRepos/integrations-extras-pagespeed/venv/ez_setup.py", line 423, in main
    return _install(archive, _build_install_args(options))
  File "/Users/mattw/Projects/DatadogRepos/integrations-extras-pagespeed/venv/ez_setup.py", line 56, in _install
    with archive_context(archive_filename):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/mattw/Projects/DatadogRepos/integrations-extras-pagespeed/venv/ez_setup.py", line 107, in archive_context
    with ContextualZipFile(filename) as archive:
  File "/Users/mattw/Projects/DatadogRepos/integrations-extras-pagespeed/venv/ez_setup.py", line 91, in __new__
    return zipfile.ZipFile(*args, **kwargs)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
```

**Comment by technovangelist** [comment]
not sure if its related, but then the next command gets me:
```
 > source venv/bin/activate
Missing end to balance this if statement
venv/bin/activate (line 78): if [ -n "$BASH" -o -n "$ZSH_VERSION" ] ; then
                             ^
from sourcing file venv/bin/activate
        called on standard input

source: Error while reading file 'venv/bin/activate'
```
