### ISSUE TITLE
Speedtest plugin issue on two Ubuntu servers

### ISSUE THREAD

**Issue by AdeTheux** [DataDog/integrations-extras#1620]
**Output of the [info page](https://docs.datadoghq.com/agent/guide/agent-commands/#service-status)**

```text
 Instance ID: speedtest:d884b5186b651429 [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/speedtest.d/conf.yaml
      Total Runs: 16,641
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 327ms
      Last Execution Date : 2022-12-05 14:50:40 CET / 2022-12-05 13:50:40 UTC (1670248240000)
      Last Successful Execution Date : Never
      Error: not all arguments converted during string formatting
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/speedtest/speedtest.py", line 31, in check
          payload = self._call_command(cmd)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/speedtest/speedtest.py", line 62, in _call_command
          payload = json.loads(result.strip())
        File "/opt/datadog-agent/embedded/lib/python3.8/json/__init__.py", line 357, in loads
          return _default_decoder.decode(s)
        File "/opt/datadog-agent/embedded/lib/python3.8/json/decoder.py", line 337, in decode
          obj, end = self.raw_decode(s, idx=_w(s, 0).end())
        File "/opt/datadog-agent/embedded/lib/python3.8/json/decoder.py", line 355, in raw_decode
          raise JSONDecodeError("Expecting value", s, err.value) from None
      json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 1122, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/speedtest/speedtest.py", line 42, in check
          self.log.exception(msg, e)
        File "/opt/datadog-agent/embedded/lib/python3.8/logging/__init__.py", line 1829, in exception
          self.log(ERROR, msg, *args, exc_info=exc_info, **kwargs)
        File "/opt/datadog-agent/embedded/lib/python3.8/logging/__init__.py", line 1844, in log
          self.logger.log(level, msg, *args, **kwargs)
        File "/opt/datadog-agent/embedded/lib/python3.8/logging/__init__.py", line 1512, in log
          self._log(level, msg, args, **kwargs)
        File "/opt/datadog-agent/embedded/lib/python3.8/logging/__init__.py", line 1589, in _log
          self.handle(record)
        File "/opt/datadog-agent/embedded/lib/python3.8/logging/__init__.py", line 1599, in handle
          self.callHandlers(record)
        File "/opt/datadog-agent/embedded/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
          hdlr.handle(record)
        File "/opt/datadog-agent/embedded/lib/python3.8/logging/__init__.py", line 954, in handle
          self.emit(record)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/log.py", line 102, in emit
          message = self.format(record)
        File "/opt/datadog-agent/embedded/lib/python3.8/logging/__init__.py", line 929, in format
          return fmt.format(record)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/log.py", line 79, in format
          message = to_native_string(super(CheckLogFormatter, self).format(record))
        File "/opt/datadog-agent/embedded/lib/python3.8/logging/__init__.py", line 668, in format
          record.message = record.getMessage()
        File "/opt/datadog-agent/embedded/lib/python3.8/logging/__init__.py", line 373, in getMessage
          msg = msg % self.args
      TypeError: not all arguments converted during string formatting
```

**Additional environment details (Operating System, Cloud provider, etc):**
Happens on two different boxes:
one Raspberry Pi with Ubuntu: 22.04.1 LTS (GNU/Linux 5.15.0-1018-raspi aarch64) and DD Agent v7.40.1
one VPS with Ubuntu: buntu 22.04.1 LTS (GNU/Linux 5.15.0-53-generic x86_64) and DD Agent v7.40.1

**Steps to reproduce the issue:**
1. datadog-agent integration install -t datadog-speedtest==1.0.0
2. sudo -u dd-agent speedtest to accept the ToS
3. speedtest.d/conf.yaml based on the template found here
4. sudo service datadog-agent restart
5. Error above appears in the agent status page

**Describe the results you received:**
Error: not all arguments converted during string formatting

**Describe the results you expected:**
Seeing data from this plugin appearing in DD dashboard

**Comment by mrsiejas** [comment]
Having exact same issue. I run `sudo datadog-agent check speedtest -l debug --check-rate`

First issue related to arguments  passed to the speedtest cli. Incorrect speedtest cli version?
```
2023-02-07 07:40:24 UTC | CORE | DEBUG | (pkg/collector/python/check.go:84 in runCheck) | Running python check speedtest (version: '1.0.0', id: 'speedtest:e3fbdaf6bed0cd0c')
usage: speedtest [-h] [--no-download] [--no-upload] [--single] [--bytes]
                 [--share] [--simple] [--csv] [--csv-delimiter CSV_DELIMITER]
                 [--csv-header] [--json] [--list] [--server SERVER]
                 [--exclude EXCLUDE] [--mini MINI] [--source SOURCE]
                 [--timeout TIMEOUT] [--secure] [--no-pre-allocate]
                 [--version]
speedtest: error: unrecognized arguments: -f json -p no -A -P 8
2023-02-07 07:40:26 UTC | CORE | DEBUG | (pkg/collector/python/check.go:84 in runCheck) | Running python check speedtest (version: '1.0.0', id: 'speedtest:e3fbdaf6bed0cd0c')
usage: speedtest [-h] [--no-download] [--no-upload] [--single] [--bytes]
                 [--share] [--simple] [--csv] [--csv-delimiter CSV_DELIMITER]
                 [--csv-header] [--json] [--list] [--server SERVER]
                 [--exclude EXCLUDE] [--mini MINI] [--source SOURCE]
                 [--timeout TIMEOUT] [--secure] [--no-pre-allocate]
                 [--version]
speedtest: error: unrecognized arguments: -f json -p no -A -P 8
```

and the config formatting - even though used the same as example from docs. Why does the script use `json.decoder` if the config file is yaml fromatt?
```
speedtest (1.0.0)
-----------------
Instance ID: speedtest:e3fbdaf6bed0cd0c [ERROR]
Configuration Source: file:/etc/datadog-agent/conf.d/speedtest.d/conf.yaml
...
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by mrsiejas** [comment]
What we need is a working example on the docs page, also how to debug it.Nice to have are sensible defaults - so even if yaml config file is empty it should work.

**Comment by mrsiejas** [comment]
Looks like I managed to resolve the errors by replacing speedtest executable - previously had one installed by Debian repos. 
```
which speedtest
/usr/bin/speedtest
rm /usr/bin/speedtest

apt remove speedtest-cli
```
and used official bin from ookla as [descibed here](https://www.speedtest.net/apps/cli)

```
sudo apt-get install curl
curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
sudo apt-get install speedtest
```

now my executable is 
```
speedtest --version
Speedtest by Ookla 1.2.0.84 (ea6b6773cf) Linux/x86_64-linux-musl 5.15.0-1028-aws x86_64

The official command line client for testing the speed and performance
of your internet connection.```

Restarted the agent service and don't see the errors in debug command anymore.

**Comment by mrsiejas** [comment]
@AdeTheux have you changed the example? I did
```
pwd
/etc/datadog-agent/conf.d/speedtest.d
wget https://raw.githubusercontent.com/DataDog/integrations-extras/master/speedtest/datadog_checks/speedtest/data/conf.yaml.example
mv conf.yaml.example conf.yaml 
chwon dd-agent:dd-agent conf.yaml
```
Then restarted the service but still seeing some nasty python stack traces in DD GUI, can't see any speedtest.* metrics either.

**Comment by mrsiejas** [comment]
The "nasty" stack trace. I think I am going to give up soon.. I would expect DD using compiled language like Go with all libs included to avoid these type of situations. Running integrations in python without controlled runtime like container is asking for trouble and make your customers leave.

**Comment by AdeTheux** [comment]
@mrsiejas I tried so many things over the last few weeks, I don't even remember where I found the template for the yaml file. But my previous version seemed to cause the problem as the one I use now on 2 different Ubuntu boxes works fine.

Just changed the "min_collection_interval"

And I have Python 3.10.6 on those 2 servers.

```
## All options defined here are available to all instances.
#
init_config:

## Every instance is scheduled independent of the others.
#
instances:

  -
    ## @param tags - list of strings - optional
    ## A list of tags to attach to every metric and service check emitted by this instance.
    ##
    ## Learn more about tagging at https://docs.datadoghq.com/tagging
    #
    # tags:
    #   - <KEY_1>:<VALUE_1>
    #   - <KEY_2>:<VALUE_2>

    ## @param min_collection_interval - number - optional - default: 15
    ## This changes the collection interval of the check. For more information, see:
    ## https://docs.datadoghq.com/developers/write_agent_check/#collection-interval
    #
    min_collection_interval: 900

    ## @param empty_default_hostname - boolean - optional - default: false
    ## This forces the check to send metrics with no hostname.
    ##
    ## This is useful for cluster-level checks.
    #
    # empty_default_hostname: false

    ## @param host - string - optional - default: foo.example.com
    ## Specify a server, from the speedtest server list, using its host's fully qualified domain name.
    ##
    ## Default is for the utility to automatically select.
    #
    # host: foo.example.com

    ## @param ip - string - optional - default: 1.2.3.4
    ## Attempt to bind to the specified IP address when connecting to servers.
    ##
    ## Default is for the utility to automatically select.
    #
    # ip: 1.2.3.4

    ## @param interface - string - optional - default: eth0
    ## Attempt to bind to the specified interface when connecting to servers.
    ##
    ## Default is for the utility to automatically select.
    #
    # interface: eth0

    ## @param server_id - integer - optional - default: 1234
    ## Specify a server from the server list using its id.
    ##
    ## Default is for the utility to automatically select.
    #
    # server_id: 1234

```
