### ISSUE TITLE
reboot_required integration errors on install

### ISSUE THREAD

**Issue by rjhornsby** [DataDog/integrations-extras#1732]
**Output of the [info page](https://docs.datadoghq.com/agent/guide/agent-commands/#service-status)**

```text
===============
Agent (v7.41.1)
===============

  Status date: 2023-01-19 22:09:09.033 EST / 2023-01-20 03:09:09.033 UTC (1674184149033)
  Agent start: 2023-01-19 20:25:47.497 EST / 2023-01-20 01:25:47.497 UTC (1674177947497)
  Pid: 4260
  Go Version: go1.18.9
  Python Version: 3.8.14
  Build arch: amd64
  Agent flavor: agent
  Check Runners: 4
  Log File: /var/log/datadog/agent.log
  Log Level: INFO
...
```

Remainder of output posted as a [gist](https://gist.github.com/rjhornsby/db3c95ec75e5c13a94db6dea09880b87) for brevity.

**Additional environment details (Operating System, Cloud provider, etc):**

vanilla Rocky 8.7, aws

**Steps to reproduce the issue:**

`sudo -u dd-agent datadog-agent integration install datadog-reboot_required==1.0.0`

or use the datadog-chef cookbook with the `datadog_integration` resource - same result either way.

1. Attempt to install the datadog-reboot_required integration
2. Get error about "rootlayout" being wrong, stacktrace below

**Describe the results you received:**

With a bit of extra debug info using `logging.basicConfig(level=logging.DEBUG)`
```
DEBUG:datadog_checks.downloader.download:simple/datadog-reboot-required/index.html has not been updated
INFO:datadog_checks.downloader.download:TUF verified simple/datadog-reboot-required/index.html
INFO:datadog_checks.downloader.download:TUF verified simple/datadog-reboot-required/datadog_reboot_required-1.0.0-py2.py3-none-any.whl
DEBUG:datadog_checks.downloader.download:in-toto-metadata/5.core.root.layout has not been updated
INFO:datadog_checks.downloader.download:TUF verified in-toto-metadata/5.core.root.layout
DEBUG:datadog_checks.downloader.download:in-toto-pubkeys/deb3476dab02f7fc9ba242c47f490346aaed1f0e6b052388008358440d21a93e.pub has not been updated
INFO:datadog_checks.downloader.download:TUF verified in-toto-pubkeys/deb3476dab02f7fc9ba242c47f490346aaed1f0e6b052388008358440d21a93e.pub
DEBUG:datadog_checks.downloader.download:in-toto-pubkeys/179284f7c9bbbaeb0e75197c2c0f7b44973b747f18959d568b46575deb982b1d.pub has not been updated
INFO:datadog_checks.downloader.download:TUF verified in-toto-pubkeys/179284f7c9bbbaeb0e75197c2c0f7b44973b747f18959d568b46575deb982b1d.pub
DEBUG:datadog_checks.downloader.download:in-toto-pubkeys/90e40ad9eed93f8d8e5156ed38c067feccc64a750411612cad71da6d7cfd1f65.pub has not been updated
INFO:datadog_checks.downloader.download:TUF verified in-toto-pubkeys/90e40ad9eed93f8d8e5156ed38c067feccc64a750411612cad71da6d7cfd1f65.pub
Traceback (most recent call last):
  File "/opt/datadog-agent/embedded/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/datadog-agent/embedded/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/downloader/__main__.py", line 9, in <module>
    sys.exit(download())
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/downloader/cli.py", line 124, in download
    wheel_abspath = tuf_downloader.download(wheel_relpath)
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/downloader/download.py", line 282, in download
    return self.__download_with_tuf_in_toto(target_relpath)
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/downloader/download.py", line 269, in __download_with_tuf_in_toto
    self.__download_and_verify_in_toto_metadata(target_relpath, target_abspath, target)
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/downloader/download.py", line 252, in __download_and_verify_in_toto_metadata
    link_abspaths = self.__download_in_toto_links(target, target_relpath)
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/downloader/download.py", line 194, in __download_in_toto_links
    link_abspaths = self.__download_custom(target, '.link')
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/downloader/download.py", line 155, in __download_custom
    raise IncorrectRootLayoutType(root_layout_type, self.__root_layout_type)
datadog_checks.downloader.exceptions.IncorrectRootLayoutType: Incorrect type, found extras, expected core. Make sure to use the -t/--third-party flag when (and only when) downloading third-party integrations.
```

**Describe the results you expected:**

The integration to install properly. Not clear from the output what "IncorrectRootLayoutType" means or if the code should even be hitting `__download_custom` since this is a 1st party integration.

**Comment by rjhornsby** [comment]
Problem does not seem to be platform-specific. Vanilla Ubuntu, fresh agent install - same error:

```
sudo -u dd-agent datadog-agent integration install datadog-reboot_required==1.0.0
...
datadog_checks.downloader.exceptions.IncorrectRootLayoutType: Incorrect type, found extras, expected core. Make sure to use the -t/--third-party flag when (and only when) downloading third-party integrations.
Error: error when downloading the wheel for datadog-reboot-required 1.0.0: error running command: exit status 1
```

**Comment by yzhan289** [comment]
Hi @rjhornsby 👋 , the `reboot_required` integration is a community integration since it is not automatically included with the Agent, so you will need to install it with the `-t` flag: https://docs.datadoghq.com/agent/guide/use-community-integrations/?tab=agentv721v621.

Please try it again with
```
sudo -u dd-agent datadog-agent integration install -t datadog-reboot_required==1.0.0
```
