### ISSUE TITLE
NVML crash on latest: AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by cep21** [DataDog/integrations-extras#1773]
```
    nvml (1.0.6)
    ------------
      Instance ID: nvml:5074a15857db5ee2 [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/nvml.yaml
      Total Runs: 578
      Metric Samples: Last Run: 1, Total: 578
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 11ms
      Last Execution Date : 2023-02-23 18:54:42 UTC (1677178482000)
      Last Successful Execution Date : Never
      Error: 'str' object has no attribute 'decode'
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 1122, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/nvml/nvml.py", line 103, in check
          self.gather(instance)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/nvml/nvml.py", line 115, in gather
          tags += self.get_tags(uuid)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/nvml/nvml.py", line 207, in get_tags
          return self.known_tags.get(device_id, self.known_tags.get(device_id.decode("utf-8"), []))
      AttributeError: 'str' object has no attribute 'decode'
```

**Comment by tmart-ops** [comment]
Installing the specific requirements as done here https://github.com/DataDog/integrations-extras/blob/03a6ffb0e0f3f672cc709758f5717e9cac9416b2/nvml/tests/Dockerfile#L10 worked for me.
