### ISSUE TITLE
NEO4J check not compatible with agent version > 7.47.0

### ISSUE THREAD

**Issue by ElectricWeasel** [DataDog/integrations-extras#2150]
**Output of the [info page](https://docs.datadoghq.com/agent/guide/agent-commands/#service-status)**

```text
===============
Agent (v7.48.1)
===============

  Status date: 2023-10-24 11:42:57.604 UTC (1698147777604)
  Agent start: 2023-10-24 10:07:11.955 UTC (1698142031955)
  Pid: 1.287603e+06
  Go Version: go1.20.8
  Python Version: 3.9.18
  Build arch: amd64
  Agent flavor: agent
  Check Runners: 4
  Log Level: info

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: -1.239ms
    System time: 2023-10-24 11:42:57.604 UTC (1698147777604)

  Host Info
  =========
    bootTime: 2023-09-16 14:32:51 UTC (1694874771000)
    hostId: XXXXX
    kernelArch: x86_64
    kernelVersion: 5.14.0-284.18.1.el9_2.x86_64
    os: linux
    platform: almalinux
    platformFamily: rhel
    platformVersion: 9.2
    procs: 282
    uptime: 907h34m35s
    virtualizationRole: guest
```
**Steps to reproduce the issue:**
1. sudo -u dd-agent datadog-agent integration install -t datadog-neo4j==3.0.1
2. sudo -u dd-agent datadog-agent check neo4j

**Describe the results you received:**
```
sudo -u dd-agent datadog-agent check neo4j

Error: could not load neo4j:
* JMX Check Loader: check is not a jmx check, or unable to determine if it's so
* Python Check Loader: unable to import module 'neo4j': No module named 'neo4j'
* Core Check Loader: Check neo4j not found in Catalog

Verbose output:

2023-10-24 11:49:56 UTC | CORE | DEBUG | (pkg/collector/python/loader.go:152 in Load) | Unable to load python module - datadog_checks.neo4j: unable to import module 'datadog_checks.neo4j': Traceback (most recent call last):
  File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/neo4j/__init__.py", line 2, in <module>
    from .neo4j import Neo4jCheck
  File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/neo4j/neo4j.py", line 4, in <module>
    from .config_models import ConfigMixin
  File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/neo4j/config_models/__init__.py", line 6, in <module>
    from .instance import InstanceConfig
  File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/neo4j/config_models/instance.py", line 15, in <module>
    from . import defaults, validators
  File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/neo4j/config_models/defaults.py", line 6, in <module>
    from datadog_checks.base.utils.models.fields import get_default_field_value
ModuleNotFoundError: No module named 'datadog_checks.base.utils.models.fields'
```
**Describe the results you expected:**
Check retrieving data

**Additional information you deem important:**
This file was removed in new DD release - [https://github.com/DataDog/integrations-core/blob/7.47.0/datadog_checks_base/datadog_checks/base/utils/models/fields.py](url)

Regards
Rafał

**Comment by Kyle-Neale** [comment]
This issue should be fixed with the merge of this [PR](https://github.com/DataDog/integrations-extras/pull/2161). Please close once you're able to confirm this issue is no longer happening 🙇
