### ISSUE TITLE
[neo4j] No connection adapters were found

### ISSUE THREAD

**Issue by shanep2300** [DataDog/integrations-extras#417]
**Output of the [info page](https://docs.datadoghq.com/agent/faq/agent-commands/#agent-status-and-information)**

```text
=== Service Checks ===
[
  {
    "check": "neo4j.can_connect",
    "host_name": "i-REDACTED",
    "timestamp": 1555432622,
    "status": 2,
    "message": "Unable to fetch Neo4j stats: No connection adapters were found for 'REDACTED'",
    "tags": [
      "server_name:neo4j-pdoqa",
      "url:REDACTED"
    ]
  }
]
=========
Collector
=========

  Running Checks
  ==============

    neo4j (unversioned)
    -------------------
      Instance ID: neo4j:51fb41f6fab9b43e [ERROR]
      Total Runs: 1
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 1
      Average Execution Time : 1ms
      Error: Unable to fetch Neo4j stats: No connection adapters were found for 'REDACTED'
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/base.py", line 774, in run
          self.check(copy.deepcopy(self.instances[0]))
        File "/etc/datadog-agent/checks.d/neo4j.py", line 106, in check
          raise CheckException(msg)
      CheckException: Unable to fetch Neo4j stats: No connection adapters were found for 'REDACTED'
```

**Additional environment details (Operating System, Cloud provider, etc):**
Linux CentOS

**Steps to reproduce the issue:**
1. `sudo datadog-agent check neo4j`

**Describe the results you received:**
Error seen above.

**Describe the results you expected:**
No errors and integration working with DD.

**Additional information you deem important (e.g. issue happens only occasionally):**
Had a 401 error before, but that issue was fixed. The `REDACTED` info is just the url used. Not sure what `No connection adapter were found` mean.

**Comment by shanep2300** [comment]
Stupid mistake. Needed `http://` in front of url......
