### ISSUE TITLE
AttributeError: 'module' object has no attribute 'tracemalloc_enabled'

### ISSUE THREAD

**Issue by abtreece** [DataDog/integrations-extras#476]
**Output of the [info page](https://docs.datadoghq.com/agent/guide/agent-commands/?tab=agentv6#service-status)**

```
[root@101b0f8edcb1 riak]# datadog-agent status
Getting the status from the agent.

===============
Agent (v6.13.0)
===============

  Status date: 2019-09-07 23:05:48.877481 UTC
  Agent start: 2019-09-07 23:04:39.704862 UTC
  Pid: 2125
  Go Version: go1.11.5
  Python Version: 2.7.16
  Check Runners: 4
  Log Level: info

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: -29.517ms
    System UTC time: 2019-09-07 23:05:48.877481 UTC

  Host Info
  =========
    bootTime: 2019-09-07 08:00:36.000000 UTC
    kernelVersion: 4.9.184-linuxkit
    os: linux
    platform: amazon
    platformFamily: rhel
    platformVersion: 2018.03
    procs: 69
    uptime: 15h4m6s
    virtualizationRole: guest
    virtualizationSystem: docker

  Hostnames
  =========
    hostname: 101b0f8edcb1
    socket-fqdn: 101b0f8edcb1
    socket-hostname: 101b0f8edcb1
    hostname provider: os
    unused hostname providers:
      aws: not retrieving hostname from AWS: the host is not an ECS instance, and other providers already retrieve non-default hostnames
      configuration/environment: hostname is empty
      gce: unable to retrieve hostname from GCE: Get http://169.254.169.254/computeMetadata/v1/instance/hostname: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

=========
Collector
=========



  Running Checks
  ==============

    cpu
    ---
      Instance ID: cpu [OK]
      Total Runs: 4
      Metric Samples: Last Run: 6, Total: 18
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s


    disk (2.4.0)
    ------------
      Instance ID: disk:e5dffb8bef24336f [ERROR]
      Total Runs: 4
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 1ms
      Error: 'module' object has no attribute 'tracemalloc_enabled'
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/base.py", line 545, in run
          elif 'profile_memory' in self.init_config or datadog_agent.tracemalloc_enabled():
      AttributeError: 'module' object has no attribute 'tracemalloc_enabled'

    file_handle
    -----------
      Instance ID: file_handle [OK]
      Total Runs: 4
      Metric Samples: Last Run: 5, Total: 20
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 8ms


    io
    --
      Instance ID: io [OK]
      Total Runs: 4
      Metric Samples: Last Run: 65, Total: 215
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 1ms


    load
    ----
      Instance ID: load [OK]
      Total Runs: 5
      Metric Samples: Last Run: 6, Total: 30
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s


    memory
    ------
      Instance ID: memory [OK]
      Total Runs: 4
      Metric Samples: Last Run: 17, Total: 68
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 1ms


    network (1.11.0)
    ----------------
      Instance ID: network:e0204ad63d43c949 [ERROR]
      Total Runs: 5
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 3ms
      Error: 'module' object has no attribute 'tracemalloc_enabled'
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/base.py", line 545, in run
          elif 'profile_memory' in self.init_config or datadog_agent.tracemalloc_enabled():
      AttributeError: 'module' object has no attribute 'tracemalloc_enabled'

    ntp
    ---
      Instance ID: ntp:b4579e02d1981c12 [OK]
      Total Runs: 4
      Metric Samples: Last Run: 1, Total: 4
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 4
      Average Execution Time : 2.585s


    riak_repl (0.0.3)
    -----------------
      Instance ID: riak_repl:1eac7da8b03c73b3 [ERROR]
      Total Runs: 5
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 1ms
      Error: 'module' object has no attribute 'tracemalloc_enabled'
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/base.py", line 545, in run
          elif 'profile_memory' in self.init_config or datadog_agent.tracemalloc_enabled():
      AttributeError: 'module' object has no attribute 'tracemalloc_enabled'

    uptime
    ------
      Instance ID: uptime [OK]
      Total Runs: 5
      Metric Samples: Last Run: 1, Total: 5
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s

========
JMXFetch
========

  Initialized checks
  ==================
    no checks

  Failed checks
  =============
    no checks

=========
Forwarder
=========

  Transactions
  ============
    CheckRunsV1: 4
    Dropped: 0
    DroppedOnInput: 0
    Events: 0
    HostMetadata: 0
    IntakeV1: 2
    Metadata: 0
    Requeued: 0
    Retried: 0
    RetryQueueSize: 0
    Series: 0
    ServiceChecks: 0
    SketchSeries: 0
    Success: 10
    TimeseriesV1: 4

  API Keys status
  ===============
    API key ending with 9b6bc: API Key valid

==========
Endpoints
==========
  https://app.datadoghq.com - API Key ending with:
      - 9b6bc

==========
Logs Agent
==========

  Logs Agent is not running

=========
Aggregator
=========
  Checks Metric Sample: 441
  Dogstatsd Metric Sample: 1
  Event: 1
  Events Flushed: 1
  Number Of Flushes: 4
  Series Flushed: 261
  Service Check: 45
  Service Checks Flushed: 42

=========
DogStatsD
=========
  Event Packets: 0
  Event Parse Errors: 0
  Metric Packets: 0
  Metric Parse Errors: 0
  Service Check Packets: 0
  Service Check Parse Errors: 0
  Udp Bytes: 0
  Udp Packet Reading Errors: 0
  Udp Packets: 1
  Uds Bytes: 0
  Uds Origin Detection Errors: 0
  Uds Packet Reading Errors: 0
  Uds Packets: 0

```

**Additional environment details (Operating System, Cloud provider, etc):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
Have been getting this error from the `riak_repl` check after upgrading to datadog-agent version 6.13.0. More specifically it seems to be from [breaking changes](https://github.com/DataDog/integrations-core/pull/4166) in datadog-checks-base              version 9.3.0. When the `riak_repl` check is enabled it errors and also causes `disk` and `network` checks to generate the same error.

Would like to understand the change to datadog-checks-base and what I need to modify on riak_repl to fix this issue.

**Describe the results you expected:**
no errors

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by ofek** [comment]
Hello @abtreece! `6.13` shouldn't ship that https://github.com/DataDog/integrations-core/blob/6.13.x/datadog_checks_base/CHANGELOG.md

Do you have some post-install step that upgrades `datadog-checks-base`?

**Comment by abtreece** [comment]
Upgrading the datadog-agent removes the extras checks so we're re-installing the riak_repl whl. Is it possible that the pip install is upgrading it to latest versions?

**Comment by ofek** [comment]
What command are you using to upgrade?

**Comment by abtreece** [comment]
The command used was `/opt/datadog-agent/embedded/bin/pip install -I...` and I think we're getting "burned" by the -I (aka --ignore-installed). It is reinstalling `datadog-checks-base` as well because it's a dependency of `riak_repl`. Mystery solved.

```
[root@2f94b99733e7 ~]# /opt/datadog-agent/embedded/bin/pip install -I datadog_riak_repl-0.0.3-py2-none-any.whl
Processing ./datadog_riak_repl-0.0.3-py2-none-any.whl
Collecting datadog-checks-base>=4.2.0 (from datadog-riak-repl==0.0.3)
  Downloading https://files.pythonhosted.org/packages/8a/81/88dcec21ab00a03cfcb7ff1dfda3e54a51857a3d92f133064406419a62d8/datadog_checks_base-9.3.0-py2.py3-none-any.whl (125kB)
    100% |################################| 133kB 1.3MB/s
Installing collected packages: datadog-checks-base, datadog-riak-repl
Successfully installed datadog-checks-base-9.3.0 datadog-riak-repl-0.0.3
```

**Comment by ofek** [comment]
Ah, nice! You may interested in our new installation workflow: https://github.com/DataDog/integrations-extras/tree/master/riak_repl#installation
