### ISSUE TITLE
[CI] `hbase_master` and `hbase_regionserver` tests broken

### ISSUE THREAD

**Issue by truthbk** [DataDog/integrations-extras#71]
Hi @everpeace! 

Currently the CI is broken for the `hbase` tests. Failing with the following error:

```
testCustomJMXMetric (test_hbase_master.TestHbase_master) ... 2017-07-05 14:07:21,923 | ERROR | App | Cannot connect to instance localhost:10101. java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 
	java.io.EOFException]
java.io.IOException: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 
	java.io.EOFException]
	at org.datadog.jmxfetch.Connection.connectWithTimeout(Connection.java:117)
	at org.datadog.jmxfetch.Connection.createConnection(Connection.java:61)
	at org.datadog.jmxfetch.RemoteConnection.<init>(RemoteConnection.java:56)
	at org.datadog.jmxfetch.ConnectionFactory.createConnection(ConnectionFactory.java:29)
	at org.datadog.jmxfetch.Instance.getConnection(Instance.java:162)
	at org.datadog.jmxfetch.Instance.init(Instance.java:173)
	at org.datadog.jmxfetch.App.init(App.java:511)
	at org.datadog.jmxfetch.App.main(App.java:115)
```

Are you aware of this issue? Was it working earlier and did it stop all of a sudden? If you know what may be going on, and could fix, that would be great. I know debugging Travis issues is a pain sometimes, so please let me know if I can help with anything. Also, if you don't have the bandwidth right now, let us know and I'll try to chip in where I may.

Thank you!

**Comment by everpeace** [comment]
@truthbk @jeremy-lq sorry for delayed response. I'll look into this.  The error looks connection error to jmx server.  it may be a problem in hbase cluster configuration for testing.

**Comment by everpeace** [comment]
I opened a wip pr (#74) to fix this issue.
