### ISSUE TITLE
LinkNotFoundError while installing datadog-traefik 1.0.0

### ISSUE THREAD

**Issue by JakeCooper** [DataDog/integrations-extras#918]
**Output of the [info page](https://docs.datadoghq.com/agent/guide/agent-commands/#service-status)**

```text
● datadog-agent.service - Datadog Agent
   Loaded: loaded (/lib/systemd/system/datadog-agent.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-03-30 20:19:53 UTC; 2 months 25 days ago
 Main PID: 19109 (agent)
    Tasks: 12 (limit: 4915)
   Memory: 63.1M
      CPU: 10h 10min 39.397s
   CGroup: /system.slice/datadog-agent.service
           └─19109 /opt/datadog-agent/bin/agent/agent run -p /opt/datadog-agent/run/agent.pid
```

**Additional environment details (Operating System, Cloud provider, etc):**

GCP Debian 9

**Steps to reproduce the issue:**
1. Attempt to install datadog-traefik (sudo datadog-agent integration install -r datadog-traefik==1.0.0)

The following error appears

**Describe the results you received:**

sudo datadog-agent integration install -r datadog-traefik==1.0.0
Traceback (most recent call last):
  File "/opt/datadog-agent/embedded/lib/python3.7/site-packages/datadog_checks/downloader/download.py", line 210, in __in_toto_verify
    verifylib.in_toto_verify(root_layout, root_layout_pubkeys, substitution_parameters=root_layout_params)
  File "/opt/datadog-agent/embedded/lib/python3.7/site-packages/in_toto/verifylib.py", line 1504, in in_toto_verify
    chain_link_dict = load_links_for_layout(layout, link_dir_path)
  File "/opt/datadog-agent/embedded/lib/python3.7/site-packages/in_toto/verifylib.py", line 163, in load_links_for_layout
    .format(step.name, step.threshold, len(links_per_step)))
in_toto.exceptions.LinkNotFoundError: Step 'tag' requires '1' link metadata file(s), found '0'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/datadog-agent/embedded/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/datadog-agent/embedded/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/datadog-agent/embedded/lib/python3.7/site-packages/datadog_checks/downloader/__main__.py", line 9, in <module>
    sys.exit(download())
  File "/opt/datadog-agent/embedded/lib/python3.7/site-packages/datadog_checks/downloader/cli.py", line 60, in download
    wheel_abspath = tuf_downloader.download(wheel_relpath)
  File "/opt/datadog-agent/embedded/lib/python3.7/site-packages/datadog_checks/downloader/download.py", line 261, in download
    return self.__download_with_tuf_in_toto(target_relpath)
  File "/opt/datadog-agent/embedded/lib/python3.7/site-packages/datadog_checks/downloader/download.py", line 248, in __download_with_tuf_in_toto
    self.__download_and_verify_in_toto_metadata(target_relpath, target_abspath, target)
  File "/opt/datadog-agent/embedded/lib/python3.7/site-packages/datadog_checks/downloader/download.py", line 237, in __download_and_verify_in_toto_metadata
    self.__in_toto_verify(inspection_packet, target_relpath)
  File "/opt/datadog-agent/embedded/lib/python3.7/site-packages/datadog_checks/downloader/download.py", line 212, in __in_toto_verify
    self.__handle_in_toto_verification_exception(target_relpath, e)
  File "/opt/datadog-agent/embedded/lib/python3.7/site-packages/datadog_checks/downloader/download.py", line 191, in __handle_in_toto_verification_exception
    raise RevokedDeveloper(target_relpath, IN_TOTO_ROOT_LAYOUT)
datadog_checks.downloader.exceptions.RevokedDeveloper: simple/datadog-traefik/datadog_traefik-1.0.0-py2.py3-none-any.whl (2.root.layout)
Error: error when downloading the wheel for datadog-traefik 1.0.0: error running command: exit status 1

**Describe the results you expected:**

Installation successful

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by ChristineTChen** [comment]
Hi @JakeCooper,

It looks like you're missing the `-t` `--third-party` flag.
```
Usage:
  datadog-agent integration install [package==version] [flags]

Flags:
  -h, --help          help for install
  -w, --local-wheel   install an agent check from a locally available wheel file. For your security, only use this to install wheels containing an Agent integration and coming from a known source. The Agent cannot perform any verification on local wheels.
  -t, --third-party   install a community or vendor-contributed integration
```



The following should succeed:
```
sudo datadog-agent integration install -r -t datadog-traefik==1.0.0
```
