### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by Quaternioneer** [DataDog/integrations-extras#998]
**Output of the [installation attempt](https://app.datadoghq.com/account/settings#integrations/pihole)**

```text
Traceback (most recent call last):
  File "/opt/datadog-agent/embedded/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/datadog-agent/embedded/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/downloader/__main__.py", line 9, in <module>
    sys.exit(download())
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/downloader/cli.py", line 118, in download
    wheel_relpath = tuf_downloader.get_wheel_relpath(standard_distribution_name, version=version)
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/downloader/download.py", line 323, in get_wheel_relpath
    raise NoSuchDatadogPackageVersion(standard_distribution_name, version)
datadog_checks.downloader.exceptions.NoSuchDatadogPackageVersion: datadog-pihole-1.0.0


```

Raspberry Pi 3 B
Ubuntu 20.04 LTS

**Steps to reproduce the issue:**
1. Install Datadog agent 
2.Run `sudo -u dd-agent -- datadog-agent integration install -t datadog-pihole==1.0.0`

It looks like I have the wrong version number for datadog-pihole, but I can't find a version number anywhere. Also, Datadog's website instructions are out of date for Pi Hole integration. The docs state, `datadog-agent integration install -t datadog-<INTEGRATION_NAME>==<INTEGRATION_VERSION>`, but you need to prepend `sudo -u dd-agent`

**Comment by FlorianVeaux** [comment]
Hey @Quaternioneer 
For some reason the only available version of this integration is [3.14.1](https://github.com/DataDog/integrations-extras/releases/tag/pihole-3.14.1) so you should be able to install the integration with:
`sudo -u dd-agent -- datadog-agent integration install -t datadog-pihole==3.14.1`

Unfortunately the version does not appear in the [Changelog](https://github.com/DataDog/integrations-extras/blob/master/pihole/CHANGELOG.md) of the integration, pinging the maintainer for visibility @monganai 

Also pinging our docs team internally about the unclear instructions.
